# Generated by Django 5.2.7 on 2025-11-02 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_epi', '0002_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True, verbose_name='Data de Empréstimo')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_epi.colaborador', verbose_name='Colaborador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_epi.epi', verbose_name='EPI Emprestado')),
            ],
        ),
    ]
