# Generated by Django 5.2.7 on 2025-11-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_epi', '0003_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Entrega'),
        ),
    ]
